application: oclp-622
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /$
  script: main.application

- url: /create
  script: main.application

- url: /message
  script: main.application

- url: /stream
  script: main.application

- url: /
  static_dir: static

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest
